# Site settings
title: Walrus
description: Make the most of your card cloning devices.
url: http://project-walrus.io
github_username: megabug/Walrus

# Build settings
markdown: kramdown
theme: minima

header_pages:
    - docs/getting-started.md
    - development.md
    - lumpy.md
