title: Walrus
description: Make the most of your card cloning devices.
url: https://walrus.app

github_username: TeamWalrus/Walrus

google_analytics: UA-115651889-1

markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - docs/getting-started.md
  - roadmap.md
  - lumpy.md

exclude:
  - Gemfile
  - Gemfile.lock
